spring.datasource.password=$7#LLj3T3!93K^nQO1m3
jwt.secret=QHDbtI6jbR0L8nUSu9TD75YxOinpiU77iKVNdgd4CemropmqJAuRlxO7MWkHr6dh
spring.mongodb.uri=mongodb://admin:password123@localhost:0805/polls?authSource=admin